on:
  push:
    branches:
    - hexo-content

jobs:
  hexo_job:
    name: hexo build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install
    - name: Hexo Action
      # You may pin to the exact commit or the version.
      # uses: sma11black/hexo-action@08f5143fa402cdaccf9fc016d6bc91329f082eb0
      uses: sma11black/hexo-action@v1.0.4
      with:
        # Github user name
        user_name: winterTTr
        # Github email
        user_email: winterTTr@gmail.com
        # The deploy key for Github Pages repo
        deploy_key: # default is 
        # Git commit messages to your GitHub Pages repository.
        commit_msg: publish
