on:
  push:
    branches:
    - hexo-content

jobs:
  hexo_job:
    name: hexo build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '19.x'
    - name: npm install hexo-cli
      run: npm install hexo-cli -g
    - name: npm install packages
      run: npm install
    - name: hexo generate
      run: hexo generate